'use client';

import { createContext, useContext, useEffect, useState } from 'react';

// Tətbiqin tək i18n mənbəyi - hər iki dildə bütün mətnlər buradadır.
const T = {
  az: {
    nav: {
      home: 'Ana səhifə', how: 'Necə işləyir', types: 'Qan qrupları',
      donors: 'Donorlar', requests: 'Sorğular', createRequest: 'Yeni sorğu',
      dashboard: 'Panel', login: 'Daxil ol', register: 'Qeydiyyat', logout: 'Çıxış',
    },
    hero: {
      eyebrow: 'Azərbaycan Qan Şəbəkəsi',
      h1: 'Bir damcı,', h1em: 'min həyat.',
      sub: 'Ehtiyacı olanı tap, ya da özün donor ol. Bir neçə dəqiqədə.',
      cta1: 'Donor ol', cta2: 'Qan qrupunu tap',
    },
    how: {
      title: 'Necə işləyir?', sub: 'Üç sadə addım',
      steps: [
        { num: '01', title: 'Qeydiyyat', desc: 'Adını, qan qrupunu və şəhərini bir dəqiqədə əlavə et.' },
        { num: '02', title: 'Profil', desc: 'Nə vaxt hazır olduğunu göstər, sənə əlaqə saxlanılsın.' },
        { num: '03', title: 'Kömək et', desc: 'Ehtiyacı olanlar səni tapır. Sən də onları tapa bilərsən.' },
      ],
    },
    blood: {
      title: 'Qan qrupun kimə uyğundur?', sub: 'Öz qrupunu seç, uyğunluğu bir baxışda gör.',
      selectPrompt: 'Qrupunu seç',
      gives: 'Verə bilər', receives: 'Ala bilər',
      all: 'hamısına', allFrom: 'hamısından',
      uDonor: 'Universal donor', uReceiver: 'Universal alıcı',
    },
    cta: { title: 'Bu gün başla', sub: '3 ayda bir neçə dəqiqən, bir insanın həyatı deməkdir.', btn: 'Donor ol' },
    footer: '© 2026 QanDonoru. Bütün hüquqlar qorunur.',
    login: {
      title: 'Xoş gəldin', sub: 'Hesabına daxil ol',
      email: 'E-poçt', password: 'Şifrə', btn: 'Daxil ol', loading: 'Yoxlanılır...',
      switch: 'Hesabın yoxdur?', switchLink: 'Qeydiyyatdan keç',
      serverErr: 'Bağlantı alınmadı, yenidən cəhd et.',
    },
    signup: {
      title: 'Qoşul', sub: '30 saniyəyə qeydiyyatdan keç',
      fullName: 'Ad Soyad', email: 'E-poçt', password: 'Şifrə',
      phone: 'Telefon', bloodType: 'Qan qrupu', city: 'Şəhər', select: 'Seç',
      btn: 'Qeydiyyatdan keç', loading: 'Yaradılır...',
      switch: 'Artıq üzvsən?', switchLink: 'Daxil ol',
      serverErr: 'Bağlantı alınmadı, yenidən cəhd et.',
      passwordHint: 'Ən azı 4 simvol',
    },
    donors: {
      title: 'Donorlar',
      sub: 'Şəhər və qan qrupuna görə axtar.',
      allBloodTypes: 'Bütün qruplar',
      allCities: 'Bütün şəhərlər',
      onlyAvailable: 'Yalnız hazır olanlar',
      reset: 'Sıfırla',
      loading: 'Yüklənir...',
      error: 'Yüklənmədi, yenidən cəhd et.',
      empty: 'Uyğun donor tapılmadı.',
      active: 'Hazır',
      inactive: 'Hazır deyil',
      lastDonation: 'Son donorluq',
      noInfo: '—',
      call: 'Zəng et',
      prev: 'Geri',
      next: 'İrəli',
      donor: 'Donor',
    },
    requests: {
      title: 'Sorğular',
      sub: 'Aktiv ehtiyacları gör, kömək təklif et.',
      filters: 'Filtr',
      bloodType: 'Qan qrupu',
      city: 'Şəhər',
      urgency: 'Təciliyyət',
      all: 'Hamısı',
      urgent: 'Təcili',
      normal: 'Normal',
      reset: 'Sıfırla',
      loading: 'Yüklənir...',
      empty: 'Aktiv sorğu yoxdur.',
      error: 'Yüklənmədi, yenidən cəhd et.',
      donorButton: 'Kömək təklif et',
      loginToRespond: 'Daxil ol',
      responseSuccess: 'Göndərildi.',
      responseError: 'Göndərilmədi, yenidən cəhd et.',
      phone: 'Əlaqə',
      units: 'vahid',
      hospital: 'Xəstəxana',
      call: 'Zəng et',
    },
    createRequest: {
      badge: 'Yeni sorğu',
      title: 'Qan lazımdır',
      sub: 'Detalları doldur, aktiv donorlara çatsın.',
      patientName: 'Xəstənin adı',
      bloodType: 'Qan qrupu',
      hospital: 'Xəstəxana',
      city: 'Şəhər',
      unitsNeeded: 'Neçə vahid',
      urgency: 'Təciliyyət',
      urgent: 'Təcili',
      normal: 'Normal',
      contactPhone: 'Əlaqə nömrəsi',
      note: 'Qeyd (istəyə görə)',
      submit: 'Sorğunu paylaş',
      loading: 'Paylaşılır...',
      error: 'Alınmadı, yenidən cəhd et.',
      select: 'Seç',
    },
    dashboard: {
      title: 'İdarəetmə paneli',
      sub: 'Profilini yenilə, sorğularını izlə.',
      overviewTitle: 'Ümumi baxış',
      profile: 'Profil',
      requests: 'Sorğularım',
      logout: 'Çıxış',
      save: 'Yadda saxla',
      saving: 'Saxlanılır...',
      loading: 'Yüklənir...',
      loadingRequests: 'Yüklənir...',
      noRequests: 'Hələ sorğu yoxdur.',
      error: 'Yüklənmədi.',
      saveError: 'Saxlanmadı.',
      deleteError: 'Silinmədi.',
      fullName: 'Ad Soyad',
      bloodType: 'Qan qrupu',
      city: 'Şəhər',
      phone: 'Telefon',
      lastDonation: 'Son donorluq',
      bio: 'Haqqında',
      available: 'Donorluğa hazıram',
      status: 'Status',
      active: 'Aktiv',
      fulfilled: 'Tamamlandı',
      cancelled: 'Ləğv edildi',
      delete: 'Sil',
      hospital: 'Xəstəxana',
      units: 'vahid',
      urgency: 'Təciliyyət',
      requestsCount: (n) => `${n} sorğu`,
      welcome: (name) => `Xoş gəldin, ${name}`,
      panel: 'Panel',
      navOverview: 'Baxış',
      quickLinks: 'Sürətli keçid',
      statTotal: 'Ümumi',
      statActive: 'Aktiv',
      statFulfilled: 'Tamamlanan',
      statDonorStatus: 'Status',
      tablePatient: 'Xəstə',
      tableLocation: 'Yer',
      tableUnits: 'Vahid',
      tableUrgency: 'Təciliyyət',
      tableStatus: 'Status',
      tableActions: '',
      backToSite: 'Sayta qayıt',
    },
  },
  en: {
    nav: {
      home: 'Home', how: 'How it works', types: 'Blood types',
      donors: 'Donors', requests: 'Requests', createRequest: 'New request',
      dashboard: 'Dashboard', login: 'Log in', register: 'Sign up', logout: 'Log out',
    },
    hero: {
      eyebrow: "Azerbaijan's Blood Network",
      h1: 'One drop,', h1em: 'endless lives.',
      sub: 'Find who needs help, or become a donor yourself. Takes minutes.',
      cta1: 'Become a donor', cta2: 'Find your type',
    },
    how: {
      title: 'How it works', sub: 'Three simple steps',
      steps: [
        { num: '01', title: 'Sign up', desc: 'Add your name, blood type, and city in a minute.' },
        { num: '02', title: 'Set status', desc: 'Show when you’re ready so people can reach you.' },
        { num: '03', title: 'Help out', desc: 'People in need find you. You can find them too.' },
      ],
    },
    blood: {
      title: 'Who matches your type?', sub: 'Pick your type, see the match at a glance.',
      selectPrompt: 'Choose your type',
      gives: 'Can give to', receives: 'Can receive from',
      all: 'everyone', allFrom: 'everyone',
      uDonor: 'Universal donor', uReceiver: 'Universal recipient',
    },
    cta: { title: 'Start today', sub: 'A few minutes every 3 months. One life, every time.', btn: 'Become a donor' },
    footer: '© 2026 QanDonoru. All rights reserved.',
    login: {
      title: 'Welcome back', sub: 'Log in to continue',
      email: 'Email', password: 'Password', btn: 'Log in', loading: 'Checking...',
      switch: 'No account?', switchLink: 'Sign up',
      serverErr: "Couldn't connect. Try again.",
    },
    signup: {
      title: 'Join in', sub: 'Sign up in 30 seconds',
      fullName: 'Full name', email: 'Email', password: 'Password',
      phone: 'Phone', bloodType: 'Blood type', city: 'City', select: 'Choose',
      btn: 'Sign up', loading: 'Creating...',
      switch: 'Already a member?', switchLink: 'Log in',
      serverErr: "Couldn't connect. Try again.",
      passwordHint: 'At least 4 characters',
    },
    donors: {
      title: 'Donors',
      sub: 'Search by city and blood type.',
      allBloodTypes: 'All types',
      allCities: 'All cities',
      onlyAvailable: 'Available only',
      reset: 'Reset',
      loading: 'Loading...',
      error: "Couldn't load. Try again.",
      empty: 'No matching donors.',
      active: 'Available',
      inactive: 'Not available',
      lastDonation: 'Last donation',
      noInfo: '—',
      call: 'Call',
      prev: 'Prev',
      next: 'Next',
      donor: 'Donor',
    },
    requests: {
      title: 'Requests',
      sub: 'See active needs, offer to help.',
      filters: 'Filters',
      bloodType: 'Blood type',
      city: 'City',
      urgency: 'Urgency',
      all: 'All',
      urgent: 'Urgent',
      normal: 'Normal',
      reset: 'Reset',
      loading: 'Loading...',
      empty: 'No active requests.',
      error: "Couldn't load. Try again.",
      donorButton: 'Offer to help',
      loginToRespond: 'Log in',
      responseSuccess: 'Sent.',
      responseError: "Couldn't send. Try again.",
      phone: 'Contact',
      units: 'units',
      hospital: 'Hospital',
      call: 'Call',
    },
    createRequest: {
      badge: 'New request',
      title: 'Blood needed',
      sub: 'Fill in the details, reach active donors.',
      patientName: 'Patient name',
      bloodType: 'Blood type',
      hospital: 'Hospital',
      city: 'City',
      unitsNeeded: 'Units needed',
      urgency: 'Urgency',
      urgent: 'Urgent',
      normal: 'Normal',
      contactPhone: 'Contact number',
      note: 'Note (optional)',
      submit: 'Share request',
      loading: 'Sharing...',
      error: "Couldn't submit. Try again.",
      select: 'Choose',
    },
    dashboard: {
      title: 'Dashboard',
      sub: 'Update your profile, track your requests.',
      overviewTitle: 'Overview',
      profile: 'Profile',
      requests: 'My requests',
      logout: 'Log out',
      save: 'Save',
      saving: 'Saving...',
      loading: 'Loading...',
      loadingRequests: 'Loading...',
      noRequests: 'No requests yet.',
      error: "Couldn't load.",
      saveError: "Couldn't save.",
      deleteError: "Couldn't delete.",
      fullName: 'Full name',
      bloodType: 'Blood type',
      city: 'City',
      phone: 'Phone',
      lastDonation: 'Last donation',
      bio: 'About',
      available: 'Available to donate',
      status: 'Status',
      active: 'Active',
      fulfilled: 'Fulfilled',
      cancelled: 'Cancelled',
      delete: 'Delete',
      hospital: 'Hospital',
      units: 'units',
      urgency: 'Urgency',
      requestsCount: (n) => `${n} requests`,
      welcome: (name) => `Welcome back, ${name}`,
      panel: 'Panel',
      navOverview: 'Overview',
      quickLinks: 'Quick links',
      statTotal: 'Total',
      statActive: 'Active',
      statFulfilled: 'Fulfilled',
      statDonorStatus: 'Status',
      tablePatient: 'Patient',
      tableLocation: 'Location',
      tableUnits: 'Units',
      tableUrgency: 'Urgency',
      tableStatus: 'Status',
      tableActions: '',
      backToSite: 'Back to site',
    },
  },
};

// Landing səhifəsindəki qan-qrupu uyğunluq cədvəli - tərcümə açarlarına
// (t.blood.all/allFrom/uDonor/uReceiver) birbaşa əlçatandır.
export function bloodCompatibility(t) {
  return [
    { type: 'A+', gives: ['A+', 'AB+'], receives: ['A+', 'A-', 'O+', 'O-'] },
    { type: 'A-', gives: ['A+', 'A-', 'AB+', 'AB-'], receives: ['A-', 'O-'] },
    { type: 'B+', gives: ['B+', 'AB+'], receives: ['B+', 'B-', 'O+', 'O-'] },
    { type: 'B-', gives: ['B+', 'B-', 'AB+', 'AB-'], receives: ['B-', 'O-'] },
    { type: 'O+', gives: ['O+', 'A+', 'B+', 'AB+'], receives: ['O+', 'O-'] },
    { type: 'O-', gives: [t.blood.all], receives: ['O-'], tag: t.blood.uDonor },
    { type: 'AB+', gives: ['AB+'], receives: [t.blood.allFrom], tag: t.blood.uReceiver },
    { type: 'AB-', gives: ['AB+', 'AB-'], receives: ['AB-', 'A-', 'B-', 'O-'] },
  ];
}

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('az');

  useEffect(() => {
    const stored = localStorage.getItem('lang');
    if (stored === 'az' || stored === 'en') setLang(stored);
  }, []);

  function toggle() {
    setLang((prev) => {
      const next = prev === 'az' ? 'en' : 'az';
      localStorage.setItem('lang', next);
      return next;
    });
  }

  return (
    <LanguageContext.Provider value={{ lang, t: T[lang], toggle }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage() yalnız <LanguageProvider> daxilində istifadə oluna bilər.');
  return ctx;
}
